version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: seblak-bombom-api-consumer-img
    container_name: seblak-bombom-api-consumer-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.env:/var/www/.env
    environment:
      - APP_ENV=local
    networks:
      - seblak-bombom-network

  nginx:
    image: nginx:alpine
    container_name: seblak-bombom-api-consumer-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - seblak-bombom-network        

  node:
    # platform: linux/arm64/v8 #this line is optional if you are using Mac Silicon chip (M1/M2/M3)
    build:
      context: .
      dockerfile: Dockerfile.node
    image: seblak-bombom-api-consumer-node-img
    container_name: seblak-bombom-api-consumer-node
    ports:
    - "3000:3000"
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    networks:
      - seblak-bombom-network

networks:
  seblak-bombom-network:
    name: seblak-bombom-network
    external: true
    driver: bridge
