version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-app
    ports:
      - 9000:9000 # Arahkan port 9000 host ke port 9000 di container
    environment:
      - HOST=0.0.0.0 # Pastikan Vue.js menerima koneksi dari semua host
    command: ["npx", "vite"]
